//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pesan
    {
        public string IdPesan { get; set; }
        public string Id { get; set; }
        public string IsiPesan { get; set; }
        public Nullable<System.DateTime> TanggalKirim { get; set; }
        public string Positive { get; set; }
        public string Negative { get; set; }
        public string Status { get; set; }
    }
}
