//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public string Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string Telepon { get; set; }
        public string IsActive { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Photo { get; set; }
        public string VerifyActivationCode { get; set; }
        public string UserActivationCode { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string ThemeLink { get; set; }
    }
}
